### ISSUE TITLE
New class name

### ISSUE THREAD

**Issue by firefly-cpp** [firefly-cpp/exam-lite-latex#5]
@KukovecRok, we should search for a better name for this class before moving this package to CTAN. iexam is simple and needs to be more informative. Any ideas?

**Comment by KukovecRok** [comment]
* simple-exam 
* school-exam-kit
 * multi-lang-exam
 * multi-lang-exam-template
 * school-exam-support
 * exam-guide
 * universal-school-exam
 * universal-exam
 * school-exam
 * smart-exam
 * exam-lite
 * exam-formatter-lite
 * school-exam-designer
 * school-exam-designer-lite
 * exam-prep

 @firefly-cpp I present a few ideas - any seem good ?

**Comment by firefly-cpp** [comment]
exam-lite is really nice. What do you think?

**Comment by KukovecRok** [comment]
Yes, I think, you can rename this repository. 
Also: this name is available on CTAN

**Comment by firefly-cpp** [comment]
@KukovecRok , fixed now. Exam-lite is now the new name of this package. We DO NOT currently have any specific barriers to submitting it for inclusion to CTAN. What do you think?

**Comment by KukovecRok** [comment]
@firefly-cpp I don't think so. I have prepared the package for upload to CTAN in #9 . May I?

**Comment by firefly-cpp** [comment]
Please proceed with the submission. Thanks.
